steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "***********************"
        echo "$BRANCH_NAME"
        echo "***********************"
  - id: 'tf init'
    name: 'hashicorp/terraform:0.14.8'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        terraform init || exit 1
  - id: 'tf plan'
    name: 'hashicorp/terraform:0.14.8'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        export GOOGLE_PROJECT=$(gcloud config get-value project) && terraform plan || exit 1
