DROP MATERIALIZED VIEW IF EXISTS beds_statistics;
DROP VIEW IF EXISTS requests;
DROP VIEW IF EXISTS offers;
DROP VIEW IF EXISTS accounts_info;
DROP TABLE IF EXISTS matches;
DROP TABLE IF EXISTS guests;
DROP TABLE IF EXISTS hosts;
DROP TABLE IF EXISTS accounts;