name: prod_deploy_guests_update

on:
  push:
    branches:
      - 'main'
    paths:
      - 'guests-update/main.py'

jobs:
  deploy_prod:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{secrets.PROD_DEPLOYER_KEY}}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'guests-update'
        runtime: 'python39'
        entry_point: 'fnc_target'
        memory_mb: '1024'
        region: 'europe-central2'
        env_vars: 'ACCOUNTS_TABLE_NAME=accounts,DB_CONNECTION_NAME=ukrn-hlpr:europe-central2:sql-hlpr-prd-db,GUESTS_TABLE_NAME=guests,HOSTS_TABLE_NAME=hosts,MATCHES_TABLE_NAME=matches,PROJECT_ID=ukrn-hlpr,SECRET_CONFIGURATION_CONTEXT=FUNCTIONS_CONFIGURATION_CONTEXT'
        source_dir: 'guests-update'
        project_id: ${{secrets.PROD_PROJECT_ID}}
        ingress_settings: 'ALLOW_ALL'
        service_account_email: 'gcf-sa@ukrn-hlpr.iam.gserviceaccount.com'
        timeout: '540'
        event_trigger_type: 'google.pubsub.topic.publish'
        event_trigger_resource: 'projects/ukrn-hlpr/topics/guests-update'




