name: test_deploy_guests_inactivity_timeout

on:
  push:
    branches:
      - 'test'
    paths:
      - 'guests-inactivity-timeout/main.py'

jobs:
  deploy_test:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{secrets.TEST_DEPLOYER_KEY}}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'guests-inactivity-timeout'
        runtime: 'python39'
        entry_point: 'fnc_target'
        memory_mb: '1024'
        region: 'europe-central2'
        env_vars: 'ACCOUNTS_TABLE_NAME=accounts,DB_CONNECTION_NAME=ukrn-hlpr-test:europe-central2:sql-ukr-helper-test,GUESTS_TABLE_NAME=guests,HOSTS_TABLE_NAME=hosts,MATCHES_TABLE_NAME=matches,PROJECT_ID=ukrn-hlpr-test,SECRET_CONFIGURATION_CONTEXT=FUNCTIONS_CONFIGURATION_CONTEXT,SEND_EMAIL_TOPIC=email'
        source_dir: 'guests-inactivity-timeout'
        project_id: ${{secrets.TEST_PROJECT_ID}}
        ingress_settings: 'ALLOW_ALL'
        service_account_email: 'gcf-sa@ukrn-hlpr-test.iam.gserviceaccount.com'
        timeout: '540'
        event_trigger_type: 'google.pubsub.topic.publish'
        event_trigger_resource: 'projects/ukrn-hlpr-test/topics/guests-inactivity-timeout'
