name: test_deploy_matches_create_match_sealed_notifications

on:
  push:
    branches:
      - 'test'
    paths:
      - 'matches-create-match-sealed-notifications/main.py'

jobs:
  deploy_test:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{secrets.TEST_DEPLOYER_KEY}}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'matches-create-match-sealed-notifications'
        runtime: 'python39'
        entry_point: 'fnc_target'
        memory_mb: '1024'
        region: 'europe-central2'
        env_vars: 'ACCOUNTS_TABLE_NAME=accounts,DB_CONNECTION_NAME=${{secrets.TEST_PROJECT_ID}}:europe-central2:sql-ukr-helper-test,GUESTS_TABLE_NAME=guests,HOSTS_TABLE_NAME=hosts,MATCHES_TABLE_NAME=matches,PROJECT_ID=${{secrets.TEST_PROJECT_ID}},SECRET_CONFIGURATION_CONTEXT=FUNCTIONS_CONFIGURATION_CONTEXT,SEND_EMAIL_TOPIC=email,SEND_SMS_TOPIC=sms'
        source_dir: 'matches-create-match-sealed-notifications'
        project_id: ${{secrets.TEST_PROJECT_ID}}
        ingress_settings: 'ALLOW_ALL'
        service_account_email: 'gcf-sa@${{secrets.TEST_PROJECT_ID}}.iam.gserviceaccount.com'
        timeout: '540'
        event_trigger_type: 'google.pubsub.topic.publish'
        event_trigger_resource: 'projects/${{secrets.TEST_PROJECT_ID}}/topics/matches-create-match-sealed-notifications'




