name: test_deploy_refresh_beds_stats

on:
  push:
    branches:
      - 'test'
    paths:
      - 'refresh_beds_stats/main.py'

jobs:
  deploy_test:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{secrets.TEST_DEPLOYER_KEY}}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'refresh_beds_stats'
        runtime: 'python39'
        entry_point: 'fnc_target'
        memory_mb: '1024'
        region: 'europe-central2'
        env_vars: 'DB_CONNECTION_NAME=${{secrets.TEST_PROJECT_ID}}:europe-central2:sql-ukr-helper-test,PROJECT_ID=${{secrets.TEST_PROJECT_ID}},SECRET_CONFIGURATION_CONTEXT=FUNCTIONS_CONFIGURATION_CONTEXT'
        source_dir: 'refresh_beds_stats'
        project_id: ${{secrets.TEST_PROJECT_ID}}
        ingress_settings: 'ALLOW_ALL'
        service_account_email: 'gcf-sa@${{secrets.TEST_PROJECT_ID}}.iam.gserviceaccount.com'
        timeout: '540'
        event_trigger_type: 'google.pubsub.topic.publish'
        event_trigger_resource: 'projects/${{secrets.TEST_PROJECT_ID}}/topics/refresh_beds_stats'




