name: deploy_refresh_beds_stats

on:
  push:
    paths:
      - 'refresh_beds_stats/main.py'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: //TODO '${{secrets.CREDENTIALS}}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'refresh_beds_stats'
        runtime: 'python38'
        region: 'europe-central2'
        source_dir: 'refresh_beds_stats'

