name: prod_deploy_remove-users-by-email

on:
  push:
    branches:
      - 'main'
    paths:
      - 'remove-users-by-email/main.py'

jobs:
  deploy_prod:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{secrets.PROD_DEPLOYER_KEY}}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'remove-users-by-email'
        runtime: 'python39'
        entry_point: 'fnc_target'
        memory_mb: '1024'
        region: 'europe-central2'
        env_vars: 'ACCOUNTS_TABLE_NAME=accounts,DB_CONNECTION_NAME=${{secrets.PROD_PROJECT_ID}}:europe-central2:sql-hlpr-prd-db,GUESTS_TABLE_NAME=guests,HOSTS_TABLE_NAME=hosts,MATCHES_TABLE_NAME=matches,PROJECT_ID=${{secrets.PROD_PROJECT_ID}},SECRET_CONFIGURATION_CONTEXT=FUNCTIONS_CONFIGURATION_CONTEXT,UNSUBSCRIBE_USER_TOPIC=unsubscribe-user'
        source_dir: 'remove-users-by-email'
        project_id: ${{secrets.PROD_PROJECT_ID}}
        ingress_settings: 'ALLOW_ALL'
        service_account_email: 'gcf-sa@${{secrets.PROD_PROJECT_ID}}.iam.gserviceaccount.com'
        timeout: '540'
        event_trigger_type: 'google.pubsub.topic.publish'
        event_trigger_resource: 'projects/${{secrets.PROD_PROJECT_ID}}/topics/remove-users-by-email'




