name: dev_deploy_refresh_beds_stats

on:
  push:
    branches:
      - 'dev'
    paths:
      - 'refresh_beds_stats/main.py'

jobs:
  deploy:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: ${{secrets.DEV_DEPLOYER_KEY}}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'refresh_beds_stats'
        runtime: 'python39'
        entry_point: 'fnc_target'
        region: 'europe-central2'
        source_dir: 'refresh_beds_stats'
        project_id: ${{secrets.DEV_PROJECT_ID}}
        memory_mb: '1024'
        timeout: '540'
        ingress_settings: 'ALLOW_ALL'
        service_account_email: 'gcf-sa@ukrn-hlpr-dev.iam.gserviceaccount.com'
        env_vars: 'DB_CONNECTION_NAME=ukrn-hlpr-dev:europe-central2:sql-ukr-helper-dev,PROJECT_ID=ukrn-hlpr-dev,SECRET_CONFIGURATION_CONTEXT=FUNCTIONS_CONFIGURATION_CONTEXT'
        event_trigger_type: 'providers/cloud.pubsub/eventTypes/topic.publish'
        event_trigger_resource: 'projects/ukrn-hlpr-dev/topics/refresh_beds_stats'




